public class DesenhoBarbaro {
    public static void mostrarDesenho() {
        System.out.println("                                                                   .                  ");
        System.out.println("                                                                 .++:                  ");
        System.out.println("                                                                .*+*+.                ");
        System.out.println("                                                                 *#**-                ");
        System.out.println("                                                                 *%*=                  ");
        System.out.println("                                   ....                          *%+.                  ");
        System.out.println("                                 .:+*%#*            .            %#+.                  ");
        System.out.println("                                .+######*       ..  -.          .%#+.                  ");
        System.out.println("                               :=%++*++-#.      =: .-.          -#*+.                  ");
        System.out.println("                              .=**-+#*+*#:     .=. .=.          -%*-                   ");
        System.out.println("                            ...=##+=#%##%*.:. .-=..--           *#*-                   ");
        System.out.println("                         .-*##*+%@%##%%%%%@=+==++:=+:           ##*.                   ");
        System.out.println("                     .:+######%##%##%%@@%@@%*##**#++.          -##*.                   ");
        System.out.println("                    :=+##%%%##%%%%###%%%%%%%%*=####-.          :##+                    ");
        System.out.println("                     -######%%%%%%*+++***#%%%%#%%#*=.          =%#+                    ");
        System.out.println("                    .=###%%%%%%%%%%#*++*=+%%*#####*+-.        .#%#*=:                  ");
        System.out.println("                   .:+#**###*%%%%%##*#**+*%@%%%%#*+=++---+#*#+%%%#*-:                  ");
        System.out.println("                   .:+*####%@@@@%%%%####%%@%%.+%%#*****##%%%%%%%%*++.                  ");
        System.out.println("                  .-=++*#%*:#%%######*%%%%%@+  :*#%##*#%%%%%@%@%##=                    ");
        System.out.println("                  =%%%#%%*=-.-#***++*##*%%%#+.    .#%##%@@@@%%%%##.                    ");
        System.out.println("                 .+%%%#%%#++-=###*++**--****#-.  .  .-=###%%-.+%#=                    ");
        System.out.println("                  =%%%%%%%*%%***%%#***==+*#%%#*. .-           =%*=                    ");
        System.out.println("                   .+*%##%@%%%*#***###*++###%@#. .=.         .%%*+                    ");
        System.out.println("                        .*%%#*##+++*+*===*#%%@%= .:.          #%#.                    ");
        System.out.println("                          .+*#%#*++##%%*+*#+*###=--          .%##.                    ");
        System.out.println("                          .-+*#%%#%@@@@*+#*=*=--#+.          #%##.                    ");
        System.out.println("                         :--+####%%%%%%@%%@%%#%%*=.          =%#+                      ");
        System.out.println("                         .:#%#+*#%#%%%@@%%@@%%#%#.+-         *%#-                      ");
        System.out.println("                         :*#%%#%@%%###%%%@@@%%%%%= #=       .%%#=                      ");
        System.out.println("                         +#%#%%%@%%%%@@@@@%%%%%%%#-+=       .%%*.                      ");
        System.out.println("                        .-#%%%##@*+%%%@@%%#%*%@%%%%*.       :%#+                       ");
        System.out.println("                       ..+**#*#@%#+%%%%%@%%%#%@%#*:         =%#*                       ");
        System.out.println("                       .=***#%%%%%*%@%%%@%%@#%@@#+:         -##-                       ");
        System.out.println("                      .-+*#@%%##%%*%@@@@@%%@#%@@%*.         +%#-                       ");
        System.out.println("                      .:. +@%%%@@@#%@@@@@@@%%@%@@*.        .+#=:      .:               ");
        System.out.println("                          -%%%@@@@##@@@@@@@%%@%%%=         :#*..     .-...            ");
        System.out.println("                          =%%%@@%@%#@@@@@@@%@@%%*-         +%**.    :-:...            ");
        System.out.println("                        -=+%%%@@@%:=#@%#%@@@@@%%#=         ##=:.   -=-:....           ");
        System.out.println("                        .#%%###%%#:     .%@@##%%#%#.     .#%#++:  :**=::...           ");
        System.out.println("                        .#++*#%%%+      .#@%##%%##=       +#+++:  :#**+:::..          ");
        System.out.println("                        *%#**%%%#-      .*@###%%#*-     .*#%***: .+##*+=::.           ");
        System.out.println("                       .=###%@@@%-       *%##%%%%#.    .#####=:-+++*#*+=::.           ");
        System.out.println("                      .=##**#%%%#=     .-+%%**###*.    :#%##+-::=****+==::.           ");
        System.out.println("                       .#%#%%%%%*=     .:+***##%%-.    .#%%#+==+==+*++==+-:.          ");
        System.out.println("                        =%%%%%#*::      .*%%%@@@#.      .#%%%%%%%%%#**+++:...         ");
        System.out.println("                        +%%%@@%:         -%@%%@%.        .#%###%##%%#%%%#-...         ");
        System.out.println("                        .#%%%%%.         .*%%%%%.        :%%++   =*####%#**=.         ");
        System.out.println("                        .#@@@@*          :*%%@%*         =%%*+    =*####*++=.         ");
        System.out.println("                       .=#%%@@*         .=#%%%%%+        :#*+:   .+#####*+=:          ");
        System.out.println("                        .*#%%#=.         +%%%%###*+.     .*=:   .*#####*+=-           ");
        System.out.println("                        :+-*#%.         .+#%####===++.   .++.   .##%%#*+==.           ");
        System.out.println("                        .:=###+            . :**++=++-    ==    .*##**+=-.            ");
        System.out.println("                       .-==*##-                           -.     +**+==:               ");
        System.out.println("                                                                 +++=-.                ");
        System.out.println("                                                                 --:.             ");
    }
}
