public class DesenhoFinalMilitar {
    public static void exibirDesenhoFinalMilitar() {
        System.out.println("                                                                        =.                           ");
        System.out.println("                                                                       -@@                           ");
        System.out.println("                                                                      +@@@                           ");
        System.out.println("                                                                     *@@@                            ");
        System.out.println("                                                                   :#@@=                             ");
        System.out.println("                                                                  *%%-                               ");
        System.out.println("                                                                =%@-                                 ");
        System.out.println("                                                              :#%-                                   ");
        System.out.println("                                                           .+#@=                                     ");
        System.out.println("                                                        .%@@@@=                                      ");
        System.out.println("                                                        :@@@%                                        ");
        System.out.println("                                                       .%@%                                          ");
        System.out.println("                                                       +@@:                                          ");
        System.out.println("                                  .=*%##.            -@@@*       .-:                                 ");
        System.out.println("                                -@@@@@@=            *@@@*     =#%%#%@%#@%++ **                       ");
        System.out.println("                               +@@@@@@@@=          *@@@=     +%%@@@@@@@@@@@@@@+#@+                   ");
        System.out.println("                              .*@@%@@@@@@%=       #@@@-     .=%@@@@@@@@@@@@@@@@@                     ");
        System.out.println("                              -%@@%@@@@@@@@#.  :%@@@@+    :*@@@@@@@@@@@@@@@@@@@%                     ");
        System.out.println("                               *@@@@@@@@@@@%=*@@@@@@@:  .+#@@@@@@@@@@@@@@@@@@@@@=                    ");
        System.out.println("                           +@@@:-#@%*%@@@@@%@@@@@@@@+  =##%@@@@@@@@@@@@@@@@@@@@@                     ");
        System.out.println("                         -@###=:=-.%=:%@@@@@@@@@@@%:.:#@@%@@@@@@@@@@@@@@@@@@@@@.                    ");
        System.out.println("                         *@=  .=  *%#%@@@@@@@@@@@@#--:+#@@@@@@@@@@@@@@@@@@@@@@%                      ");
        System.out.println("                         %@%.  =@@@@@@@@@@@@@@@@@@#  -#%@@@@@@@@@@@@@@@#@@@@@@%                      ");
        System.out.println("                         %@@@#@@@@@@@@@@@@@@@@@@@@@+%@@@@@@@@@@@@@@@@@*  @@@@@@:                     ");
        System.out.println("                         +@@@@@@@@@@@@@@@@@@@@@@@@@%*@@@@@@@@@@@@@@@@@+.=%@@@@@+                     ");
        System.out.println("                          ****#%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+  =@@@@+                      ");
        System.out.println("                             -#@@@@@@@@=-#@@@@@@@@@@@@@@@@@@@@@@@@@@@@*-.   .                        ");
        System.out.println("       :+**#***+++======+*%@@@@@@@@@@+    :@@@@@@@@@@@@@@@@@@@@@@@@@@@:                              ");
        System.out.println("    .#@@@@@@@@@@@@@@@@@@@@@@@@%@@@@#       *@@@@@@@@@@@@@@@@@@@@@@@@@@=                              ");
        System.out.println("   =@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%         =@@@@@@@@@@@@@@@@@@@@@@@@@@@+                             ");
        System.out.println("  -@@@@@@@@@@@@@@@@@@@@@@@@@@@@+       :+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@-                            ");
        System.out.println("  %@@@@@@@@@%+:    .-=*##%#*=   :+%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#                            ");
        System.out.println(" -@@@@@@@*:                  =%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+*%@@@@@*                   ");
        System.out.println(" %@@@@@-                   +@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*==#@@+                 ");
        System.out.println(" .@@@%.                .=*#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%:      -%@%-              ");
        System.out.println(" =@%.              .#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*           *@@-            ");
        System.out.println(" #:             .%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*         #@-           ");
        System.out.println("              #@@@@@@#=@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@@@        @@%:          ");
        System.out.println("             @@@@@@@@:*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%=--.           *@@:        +*=          ");
        System.out.println("            %@@@@@@@@ *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@-             *@#                        ");
        System.out.println("           -@@@@@@@@@.-@@@@@@@@@@@@@@@@@@@@%*+=--:..  .*#%%.            :%@*                         ");
        System.out.println("           *@@@@@@@=-: +@@@@@@@@@@@@@@@@@@@*                       .*:.#@@#                          ");
        System.out.println("           #@@@@@@@ -   +@@@@@@@@@@@@@@@@@@*                      *@@@@#-                            ");
        System.out.println("           *@@@@@+*-     =@@@@@@@@%@@@@@@@#                       -                                  ");
        System.out.println("           +@@@@@# .-     +@@@@@@= =@@@@@%                                                           ");
        System.out.println("          +@@@@@@@+       +@@@@@=  #@@@@@:                                                           ");
        System.out.println("          *@@@@@@@*       @@@@@=  :@@@@@=                                                            ");
        System.out.println("         =@@@@@@@@#     :%@@@%.  :@@@@@-                                                             ");
        System.out.println("        =#+%@@@@#.#    *@@@@#   -@@@@@.                                                              ");
        System.out.println("       +-#*%@@-:=:-    *@@@%    .@@@@*                                                               ");
        System.out.println("       =++@@+   +:     -@@@.      @@@=                                                               ");
        System.out.println("       -@# *= .  :      #@#        %@#                                                               ");
        System.out.println("      :+@= -.           *@#        :@@=                                                              ");
        System.out.println("      .:*  .=           +@@         =@@-                                                             ");
        System.out.println("        : . .           =@@:         *@@-                                                            ");
        System.out.println("                        =@@%         .%@@-                                                           ");
        System.out.println("                         +@@=         .+%@=                                                          ");
        System.out.println("                          =@@*           @@@:                                                        ");
        System.out.println("                          -@@@-          -%@#.                                    ");
    }
}
